version: "3.8"

services:
  # MySQL databases for each service
  mysql:
    image: mysql:8.0
    container_name: bookquik-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bookquik
      MYSQL_USER: bookquik_user
      MYSQL_PASSWORD: bookquik_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bookquik-network

  # Kafka
  kafka:
    image: apache/kafka:4.0.0
    container_name: bookquik-kafka-broker
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - bookquik-network

  # Kafka UI for management and monitoring
  kafbat:
    image: ghcr.io/kafbat/kafka-ui:latest
    container_name: bookquik-kafbat
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: bookquik-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - bookquik-network

  # Keycloak for authentication and authorization
  keycloak:
    image: quay.io/keycloak/keycloak:21.0
    container_name: bookquik-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/keycloak
      KC_DB_USERNAME: bookquik_user
      KC_DB_PASSWORD: bookquik_password
    command:
      - start-dev
    ports:
      - "8180:8080"
    depends_on:
      - mysql
    networks:
      - bookquik-network

networks:
  bookquik-network:
    driver: bridge

volumes:
  mysql-data:
  zookeeper-data:
  zookeeper-logs:
  kafka-data:
